### ISSUE TITLE
开箱即用的组件应该将核心依赖 @wangeditor/editor 声明成  dependencies 

### ISSUE THREAD

**Issue by echoLC** [wangeditor-team/wangEditor-for-vue#5]
## 背景
关联 [issue](https://github.com/wangeditor-team/wangEditor-v5/issues/440)，否则用户安装完 `@wangeditor/editor-for-vue` 还需要单独安装 `@wangeditor/editor` ，带来额外的使用成本。对于小白用户，也容易出现因为依赖安装不够，导致意外的报错。

**Comment by wangfupeng1988** [comment]
如微信沟通，已经解决。
