### ISSUE TITLE
有问题可以先参考该demo，如果无法解决您的问题，可以提对应的Issue

### ISSUE THREAD

**Issue by callqh** [wangeditor-team/wangEditor-for-vue#8]
📌 [wangEditor-vue2-demo](https://codesandbox.io/s/wangeditor-vue2-demo-0v7gbp)

**Comment by akalsy** [comment]
如何设置语言，求解答！

**Comment by akalsy** [comment]
> 如何设置语言，求解答！

找到答案了：
import { i18nChangeLanguage } from '@wangeditor/editor'  
 onCreated(editor) {
        i18nChangeLanguage('en')
    }

**Comment by callqh** [comment]
> 如何设置语言，求解答！

参考官网文档： https://www.wangeditor.com/v5/i18n.html
